name: Maptime AMS
baseurl:

animation-interval: 5500
building-stroke-width: 8

venue: Waag Society, Nieuwmarkt 4
venue-url: "https://www.openstreetmap.org/#map=19/52.37268/4.90042"

next-event: February 18th
next-event-url: http://www.meetup.com/Maptime-AMS/events/218595562/

links:
  - title: Maptime HQ
    url: http://maptime.io/

  - title: Meetup
    url: http://www.meetup.com/Maptime-AMS

  - title: Twitter
    url: https://twitter.com/MaptimeAMS

  - title: Waag Society
    url: http://waag.org/

  - title: GitHub
    url: https://github.com/maptime-ams/maptime-ams.github.io

  - title: Resources
    url: https://github.com/maptime-ams

collections:
  meetups:
    output: true
    permalink: /meetups/:path/

defaults:
  - scope:
      path: meetups
    values:
      layout: presentation
