name: Maptime AMS
baseurl:

animation-interval: 5500
building-stroke-width: 8

venue: Waag, Nieuwmarkt 4
venue-url: "https://www.openstreetmap.org/#map=19/52.37268/4.90042"

links:
  - title: Maptime HQ 
    url: http://maptime.io/

  - title: Meetup
    url: http://www.meetup.com/Maptime-AMS

  - title: Twitter
    url: https://twitter.com/MaptimeAMS

  - title: GitHub
    url: https://github.com/maptime-ams

  - title: Waag
    url: http://waag.org/

collections:
  meetups:
    output: true
    permalink: /meetups/:path/

defaults:
  - scope:
      path: meetups
    values:
      layout: presentation
